"""Akamai mTLS Trust Store API client package.

Provides access to the Akamai mTLS Truststore v2 API for managing CA sets,
CA set versions, activations, and certificate validation.

Mirrors the Go ``pkg/mtlstruststore`` package public API surface.
"""
# pylint: disable=redefined-builtin

# Re-export the Client class -------------------------------------------
from akamai.edgegrid.mtlstruststore.mtlstruststore import Client

# Re-export all model classes, type aliases, and constants ---------------
from akamai.edgegrid.mtlstruststore.models import (
    # Type aliases (Go type definitions)
    Network,
    AssociationType,
    CertificateStatus,
    VersionStatus,
    ActivationNetwork,
    # Network constants (ca_set.go)
    NETWORK_INACTIVE,
    NETWORK_STAGING,
    NETWORK_PRODUCTION,
    NETWORK_STAGING_AND_PRODUCTION,
    NETWORK_PRODUCTION_AND_STAGING,
    NETWORK_STAGING_OR_PRODUCTION,
    NETWORK_PRODUCTION_OR_STAGING,
    # CA Set Name constants (ca_set.go)
    CA_SET_NAME_PATTERN,
    CA_SET_NAME_DESCRIPTION,
    # Deletion status constants (ca_set.go)
    DELETION_STATUS_IN_PROGRESS,
    DELETION_STATUS_COMPLETE,
    DELETION_STATUS_FAILED,
    # CA Set status constants (ca_set.go)
    CA_SET_STATUS_NOT_DELETED,
    CA_SET_STATUS_DELETED,
    CA_SET_STATUS_DELETING,
    # Association type constants (ca_set.go)
    ASSOCIATION_TYPE_ENROLLMENTS,
    ASSOCIATION_TYPE_PROPERTIES,
    # Activation network constants (ca_set_activation.go)
    ACTIVATION_NETWORK_STAGING,
    ACTIVATION_NETWORK_PRODUCTION,
    # Certificate status constants (ca_set_versions.go)
    EXPIRING_CERT,
    EXPIRED_CERT,
    EXPIRED_OR_EXPIRING_CERT,
    EXPIRING_OR_EXPIRED_CERT,
    ACTIVE_CERT,
    ACTIVE_OR_EXPIRED_CERT,
    EXPIRED_OR_ACTIVE_CERT,
    # Certificate models (shared)
    CertificateRequest,
    CertificateResponse,
    Warning,
    Validation,
    # CA Set request/response models (ca_set.go)
    CreateCASetRequest,
    CASetResponse,
    CreateCASetResponse,
    GetCASetResponse,
    CloneCASetResponse,
    ListCASetsRequest,
    ListCASetsResponse,
    GetCASetRequest,
    DeleteCASetRequest,
    ListCASetAssociationsRequest,
    AssociationHostname,
    AssociationProperty,
    AssociationEnrollment,
    Associations,
    ListCASetAssociationsResponse,
    CloneCASetRequest,
    GetCASetDeletionStatusRequest,
    CASetNetworkDeleteStatus,
    GetCASetDeletionStatusResponse,
    CASetActivity,
    ListCASetActivitiesRequest,
    ListCASetActivitiesResponse,
    # CA Set Version models (ca_set_versions.go)
    CASetVersion,
    CreateCASetVersionResponse,
    CloneCASetVersionResponse,
    GetCASetVersionResponse,
    UpdateCASetVersionResponse,
    CreateCASetVersionRequest,
    CreateCASetVersionRequestBody,
    CloneCASetVersionRequest,
    ListCASetVersionsRequest,
    GetCASetVersionRequest,
    UpdateCASetVersionRequest,
    UpdateCASetVersionRequestBody,
    GetCASetVersionCertificatesRequest,
    ListCASetVersionsResponse,
    GetCASetVersionCertificatesResponse,
    # CA Set Activation models (ca_set_activation.go)
    ActivateCASetVersionRequest,
    DeactivateCASetVersionRequest,
    ActivateCASetVersionResponse,
    DeactivateCASetVersionResponse,
    GetCASetVersionActivationRequest,
    GetCASetVersionActivationResponse,
    ListCASetVersionActivationsRequest,
    ListCASetVersionActivationsResponse,
    ListCASetActivationsRequest,
    ListCASetActivationsResponse,
    # Certificate validation models (certificate.go)
    ValidateCertificate,
    ValidateCertificatesRequest,
    ValidateCertificateResponse,
    ValidateCertificatesResponse,
)

# Re-export error classes and sentinel constants -------------------------
from akamai.edgegrid.mtlstruststore.errors import (
    # Error classes
    Error,
    ErrorItem,
    ErrStructValidation,
    # Sentinel error constants — API-returned errors (errors.go)
    ErrGetCASetNotFound,
    ErrGetCASetVersionNotFound,
    ErrGetCASetActivationNotFound,
    ErrDeleteCASetNotFound,
    ErrDeleteActivationDeactivationInProgress,
    ErrCASetDeleteRequestInProgress,
    ErrCASetVersionIsActive,
    ErrCASetVersionIsActiveOnNetwork,
    ErrCASetVersionWasPreviouslyActive,
    ErrCertificateValidationFailedForCreate,
    ErrCertificateValidationFailedForUpdate,
    ErrCertificateValidationFailedForActivation,
    ErrCertificateLimitReached,
    ErrCASetVersionLimitReached,
    ErrCASetVersionIsDuplicate,
    ErrCASetBoundToHostname,
    ErrCASetInUseByHostnames,
    ErrAnotherActivationInProgress,
    ErrAnotherDeactivationInProgress,
    ErrCASetVersionNotActiveOnNetwork,
    ErrCASetVersionNotActiveOnNetworkCannotBeDeactivated,
    ErrCASetVersionIsActiveOnNetworkCannotBeActivated,
    ErrFetchAssociationsTimeout,
    ErrMissingCASetVersion,
    ErrCASetNameNotUnique,
    ErrCASetLimitReached,
    ErrNoActiveCertDeletions,
    ErrCertValidationFailure,
    ErrUnknownQueryParameters,
    ErrJSONSchemaValidation,
    ErrAnotherActivationJustCompletedIinTheCASet,
    ErrPathVariableQueryParamTypeMismatch,
    ErrUnauthorized,
    ErrInternalError,
    ErrForbidden,
    ErrCASetInUseByEnrollments,
    ErrCASetInUseByHostnamesAndNotEnrollments,
    ErrCASetInUseByBothEnrollmentsAndHostnames,
    ErrFindAssociationsFailedForEnrollmentsWithHostnamesLinked,
    ErrFindAssociationsFailed,
    ErrCASetCannotBeDeletedActiveVersions,
    ErrFindAssociationsFailedForHostnamesWithEnrollmentsLinked,
    ErrFetchAssociationsFailedForHostnames,
    ErrFetchAssociationsFailedForEnrollments,
    ErrFetchAssociationsFailed,
    ErrFindAssociationsFailedForEnrollmentsWithEmptyHostnames,
    ErrFindAssociationsFailedForHostnamesEnrollmentsNotLinked,
    ErrMediaTypeNotSupported,
    ErrMediaTypeNotAcceptable,
    ErrInvalidJSON,
    ErrInvalidField,
    ErrMissingRequiredQueryParameter,
    ErrCASetNameValidationFailure,
    # Operation sentinel errors — CA sets (ca_set.go)
    ErrCreateCASet,
    ErrGetCASet,
    ErrListCASets,
    ErrDeleteCASet,
    ErrListCASetAssociations,
    ErrCloneCASet,
    ErrGetCASetDeletionStatus,
    ErrListCASetActivities,
    ErrValidateCertificates,
    # Operation sentinel errors — CA set versions (ca_set_versions.go)
    ErrCreateCASetVersion,
    ErrCloneCASetVersion,
    ErrGetCASetVersion,
    ErrListCASetVersions,
    ErrGetCASetVersionCertificates,
    ErrUpdateCASetVersion,
    # Operation sentinel errors — activations (ca_set_activation.go)
    ErrActivateCASetVersion,
    ErrDeactivateCASetVersion,
    ErrGetCASetVersionActivation,
    ErrListCASetVersionActivations,
    ErrListCASetActivations,
)

__all__ = [
    # Client
    'Client',
    # Type aliases
    'Network',
    'AssociationType',
    'CertificateStatus',
    'VersionStatus',
    'ActivationNetwork',
    # Network constants
    'NETWORK_INACTIVE',
    'NETWORK_STAGING',
    'NETWORK_PRODUCTION',
    'NETWORK_STAGING_AND_PRODUCTION',
    'NETWORK_PRODUCTION_AND_STAGING',
    'NETWORK_STAGING_OR_PRODUCTION',
    'NETWORK_PRODUCTION_OR_STAGING',
    # CA Set Name constants
    'CA_SET_NAME_PATTERN',
    'CA_SET_NAME_DESCRIPTION',
    # Deletion status constants
    'DELETION_STATUS_IN_PROGRESS',
    'DELETION_STATUS_COMPLETE',
    'DELETION_STATUS_FAILED',
    # CA Set status constants
    'CA_SET_STATUS_NOT_DELETED',
    'CA_SET_STATUS_DELETED',
    'CA_SET_STATUS_DELETING',
    # Association type constants
    'ASSOCIATION_TYPE_ENROLLMENTS',
    'ASSOCIATION_TYPE_PROPERTIES',
    # Activation network constants
    'ACTIVATION_NETWORK_STAGING',
    'ACTIVATION_NETWORK_PRODUCTION',
    # Certificate status constants
    'EXPIRING_CERT',
    'EXPIRED_CERT',
    'EXPIRED_OR_EXPIRING_CERT',
    'EXPIRING_OR_EXPIRED_CERT',
    'ACTIVE_CERT',
    'ACTIVE_OR_EXPIRED_CERT',
    'EXPIRED_OR_ACTIVE_CERT',
    # Certificate models
    'CertificateRequest',
    'CertificateResponse',
    'Warning',
    'Validation',
    # CA Set models
    'CreateCASetRequest',
    'CASetResponse',
    'CreateCASetResponse',
    'GetCASetResponse',
    'CloneCASetResponse',
    'ListCASetsRequest',
    'ListCASetsResponse',
    'GetCASetRequest',
    'DeleteCASetRequest',
    'ListCASetAssociationsRequest',
    'AssociationHostname',
    'AssociationProperty',
    'AssociationEnrollment',
    'Associations',
    'ListCASetAssociationsResponse',
    'CloneCASetRequest',
    'GetCASetDeletionStatusRequest',
    'CASetNetworkDeleteStatus',
    'GetCASetDeletionStatusResponse',
    'CASetActivity',
    'ListCASetActivitiesRequest',
    'ListCASetActivitiesResponse',
    # CA Set Version models
    'CASetVersion',
    'CreateCASetVersionResponse',
    'CloneCASetVersionResponse',
    'GetCASetVersionResponse',
    'UpdateCASetVersionResponse',
    'CreateCASetVersionRequest',
    'CreateCASetVersionRequestBody',
    'CloneCASetVersionRequest',
    'ListCASetVersionsRequest',
    'GetCASetVersionRequest',
    'UpdateCASetVersionRequest',
    'UpdateCASetVersionRequestBody',
    'GetCASetVersionCertificatesRequest',
    'ListCASetVersionsResponse',
    'GetCASetVersionCertificatesResponse',
    # CA Set Activation models
    'ActivateCASetVersionRequest',
    'DeactivateCASetVersionRequest',
    'ActivateCASetVersionResponse',
    'DeactivateCASetVersionResponse',
    'GetCASetVersionActivationRequest',
    'GetCASetVersionActivationResponse',
    'ListCASetVersionActivationsRequest',
    'ListCASetVersionActivationsResponse',
    'ListCASetActivationsRequest',
    'ListCASetActivationsResponse',
    # Certificate validation models
    'ValidateCertificate',
    'ValidateCertificatesRequest',
    'ValidateCertificateResponse',
    'ValidateCertificatesResponse',
    # Error classes
    'Error',
    'ErrorItem',
    'ErrStructValidation',
    # Sentinel error constants — API-returned errors
    'ErrGetCASetNotFound',
    'ErrGetCASetVersionNotFound',
    'ErrGetCASetActivationNotFound',
    'ErrDeleteCASetNotFound',
    'ErrDeleteActivationDeactivationInProgress',
    'ErrCASetDeleteRequestInProgress',
    'ErrCASetVersionIsActive',
    'ErrCASetVersionIsActiveOnNetwork',
    'ErrCASetVersionWasPreviouslyActive',
    'ErrCertificateValidationFailedForCreate',
    'ErrCertificateValidationFailedForUpdate',
    'ErrCertificateValidationFailedForActivation',
    'ErrCertificateLimitReached',
    'ErrCASetVersionLimitReached',
    'ErrCASetVersionIsDuplicate',
    'ErrCASetBoundToHostname',
    'ErrCASetInUseByHostnames',
    'ErrAnotherActivationInProgress',
    'ErrAnotherDeactivationInProgress',
    'ErrCASetVersionNotActiveOnNetwork',
    'ErrCASetVersionNotActiveOnNetworkCannotBeDeactivated',
    'ErrCASetVersionIsActiveOnNetworkCannotBeActivated',
    'ErrFetchAssociationsTimeout',
    'ErrMissingCASetVersion',
    'ErrCASetNameNotUnique',
    'ErrCASetLimitReached',
    'ErrNoActiveCertDeletions',
    'ErrCertValidationFailure',
    'ErrUnknownQueryParameters',
    'ErrJSONSchemaValidation',
    'ErrAnotherActivationJustCompletedIinTheCASet',
    'ErrPathVariableQueryParamTypeMismatch',
    'ErrUnauthorized',
    'ErrInternalError',
    'ErrForbidden',
    'ErrCASetInUseByEnrollments',
    'ErrCASetInUseByHostnamesAndNotEnrollments',
    'ErrCASetInUseByBothEnrollmentsAndHostnames',
    'ErrFindAssociationsFailedForEnrollmentsWithHostnamesLinked',
    'ErrFindAssociationsFailed',
    'ErrCASetCannotBeDeletedActiveVersions',
    'ErrFindAssociationsFailedForHostnamesWithEnrollmentsLinked',
    'ErrFetchAssociationsFailedForHostnames',
    'ErrFetchAssociationsFailedForEnrollments',
    'ErrFetchAssociationsFailed',
    'ErrFindAssociationsFailedForEnrollmentsWithEmptyHostnames',
    'ErrFindAssociationsFailedForHostnamesEnrollmentsNotLinked',
    'ErrMediaTypeNotSupported',
    'ErrMediaTypeNotAcceptable',
    'ErrInvalidJSON',
    'ErrInvalidField',
    'ErrMissingRequiredQueryParameter',
    'ErrCASetNameValidationFailure',
    # Operation sentinel errors — CA sets
    'ErrCreateCASet',
    'ErrGetCASet',
    'ErrListCASets',
    'ErrDeleteCASet',
    'ErrListCASetAssociations',
    'ErrCloneCASet',
    'ErrGetCASetDeletionStatus',
    'ErrListCASetActivities',
    'ErrValidateCertificates',
    # Operation sentinel errors — CA set versions
    'ErrCreateCASetVersion',
    'ErrCloneCASetVersion',
    'ErrGetCASetVersion',
    'ErrListCASetVersions',
    'ErrGetCASetVersionCertificates',
    'ErrUpdateCASetVersion',
    # Operation sentinel errors — activations
    'ErrActivateCASetVersion',
    'ErrDeactivateCASetVersion',
    'ErrGetCASetVersionActivation',
    'ErrListCASetVersionActivations',
    'ErrListCASetActivations',
]
