"""DataStream API client for Akamai DataStream2 configuration.

See: https://techdocs.akamai.com/datastream2/reference/api
"""

from .datastream import Client
from .errors import (
    Error,
    RequestErrors,
    ErrStructValidation,
    ErrCreateStream,
    ErrGetStream,
    ErrUpdateStream,
    ErrDeleteStream,
    ErrListStreams,
    ErrActivateStream,
    ErrDeactivateStream,
    ErrGetActivationHistory,
    ErrGetProperties,
    ErrGetDatasetFields,
)
from .models import (
    AbstractConnector,
    STREAM_STATUS_ACTIVATED,
    STREAM_STATUS_DEACTIVATED,
    STREAM_STATUS_ACTIVATING,
    STREAM_STATUS_DEACTIVATING,
    STREAM_STATUS_INACTIVE,
    DELIMITER_TYPE_SPACE,
    FORMAT_TYPE_STRUCTURED,
    FORMAT_TYPE_JSON,
    INTERVAL_IN_SECONDS_30,
    INTERVAL_IN_SECONDS_60,
    DESTINATION_TYPE_AZURE,
    DESTINATION_TYPE_S3,
    DESTINATION_TYPE_DATADOG,
    DESTINATION_TYPE_SPLUNK,
    DESTINATION_TYPE_GCS,
    DESTINATION_TYPE_HTTPS,
    DESTINATION_TYPE_SUMO_LOGIC,
    DESTINATION_TYPE_ORACLE,
    DESTINATION_TYPE_LOGGLY,
    DESTINATION_TYPE_NEW_RELIC,
    DESTINATION_TYPE_ELASTICSEARCH,
    DESTINATION_TYPE_S3_COMPATIBLE,
    DESTINATION_TYPE_TRAFFIC_PEAK,
    DESTINATION_TYPE_DYNATRACE,
    AUTHENTICATION_TYPE_NONE,
    AUTHENTICATION_TYPE_BASIC,
    TRAFFIC_PEAK_CONTENT_TYPE_JSON,
    TRAFFIC_PEAK_CONTENT_TYPE_JSON_UTF8,
    Frequency,
    DeliveryConfiguration,
    DataSetField,
    DatasetFieldID,
    DataSets,
    Property,
    PropertyID,
    Destination,
    DetailedStreamVersion,
    StreamConfiguration,
    StreamUpdate,
    StreamDetails,
    ActivationHistoryEntry,
    PropertiesDetails,
    PropertyDetails,
    CreateStreamRequest,
    GetStreamRequest,
    UpdateStreamRequest,
    DeleteStreamRequest,
    ListStreamsRequest,
    ActivateStreamRequest,
    DeactivateStreamRequest,
    GetActivationHistoryRequest,
    GetPropertiesRequest,
    GetDatasetFieldsRequest,
    S3Connector,
    AzureConnector,
    DatadogConnector,
    SplunkConnector,
    GCSConnector,
    CustomHTTPSConnector,
    SumoLogicConnector,
    OracleCloudStorageConnector,
    LogglyConnector,
    NewRelicConnector,
    ElasticsearchConnector,
    S3CompatibleConnector,
    TrafficPeakConnector,
    DynatraceConnector,
)

__all__ = [
    # Client
    "Client",
    # Errors
    "Error",
    "RequestErrors",
    "ErrStructValidation",
    "ErrCreateStream",
    "ErrGetStream",
    "ErrUpdateStream",
    "ErrDeleteStream",
    "ErrListStreams",
    "ErrActivateStream",
    "ErrDeactivateStream",
    "ErrGetActivationHistory",
    "ErrGetProperties",
    "ErrGetDatasetFields",
    # Protocol
    "AbstractConnector",
    # Stream status constants
    "STREAM_STATUS_ACTIVATED",
    "STREAM_STATUS_DEACTIVATED",
    "STREAM_STATUS_ACTIVATING",
    "STREAM_STATUS_DEACTIVATING",
    "STREAM_STATUS_INACTIVE",
    # Delimiter / format / interval constants
    "DELIMITER_TYPE_SPACE",
    "FORMAT_TYPE_STRUCTURED",
    "FORMAT_TYPE_JSON",
    "INTERVAL_IN_SECONDS_30",
    "INTERVAL_IN_SECONDS_60",
    # Destination type constants
    "DESTINATION_TYPE_AZURE",
    "DESTINATION_TYPE_S3",
    "DESTINATION_TYPE_DATADOG",
    "DESTINATION_TYPE_SPLUNK",
    "DESTINATION_TYPE_GCS",
    "DESTINATION_TYPE_HTTPS",
    "DESTINATION_TYPE_SUMO_LOGIC",
    "DESTINATION_TYPE_ORACLE",
    "DESTINATION_TYPE_LOGGLY",
    "DESTINATION_TYPE_NEW_RELIC",
    "DESTINATION_TYPE_ELASTICSEARCH",
    "DESTINATION_TYPE_S3_COMPATIBLE",
    "DESTINATION_TYPE_TRAFFIC_PEAK",
    "DESTINATION_TYPE_DYNATRACE",
    # Authentication type constants
    "AUTHENTICATION_TYPE_NONE",
    "AUTHENTICATION_TYPE_BASIC",
    # TrafficPeak content type constants
    "TRAFFIC_PEAK_CONTENT_TYPE_JSON",
    "TRAFFIC_PEAK_CONTENT_TYPE_JSON_UTF8",
    # Response / data models
    "Frequency",
    "DeliveryConfiguration",
    "DataSetField",
    "DatasetFieldID",
    "DataSets",
    "Property",
    "PropertyID",
    "Destination",
    "DetailedStreamVersion",
    "StreamConfiguration",
    "StreamUpdate",
    "StreamDetails",
    "ActivationHistoryEntry",
    "PropertiesDetails",
    "PropertyDetails",
    # Request models
    "CreateStreamRequest",
    "GetStreamRequest",
    "UpdateStreamRequest",
    "DeleteStreamRequest",
    "ListStreamsRequest",
    "ActivateStreamRequest",
    "DeactivateStreamRequest",
    "GetActivationHistoryRequest",
    "GetPropertiesRequest",
    "GetDatasetFieldsRequest",
    # Connector classes
    "S3Connector",
    "AzureConnector",
    "DatadogConnector",
    "SplunkConnector",
    "GCSConnector",
    "CustomHTTPSConnector",
    "SumoLogicConnector",
    "OracleCloudStorageConnector",
    "LogglyConnector",
    "NewRelicConnector",
    "ElasticsearchConnector",
    "S3CompatibleConnector",
    "TrafficPeakConnector",
    "DynatraceConnector",
]
