"""Domain Ownership Manager API client for Akamai."""

from .domainownership import Client
from .models import (
    AddDomainsRequest,
    AddDomainsResponse,
    AddDomainError,
    AddDomainSuccess,
    CnameRecord,
    DeleteDomainRequest,
    DeleteDomainsRequest,
    Domain,
    DomainItem,
    DomainStatusHistory,
    GetDomainRequest,
    GetDomainResponse,
    HTTPFile,
    HTTPRedirect,
    InvalidateDomainRequest,
    InvalidateDomainResponse,
    InvalidateDomainsRequest,
    InvalidateDomainsResponse,
    Link,
    ListDomainsRequest,
    ListDomainsResponse,
    Metadata,
    SearchDomainItem,
    SearchDomainsBody,
    SearchDomainsRequest,
    SearchDomainsResponse,
    TXTRecord,
    ValidateDomain,
    ValidateDomainResponse,
    ValidateDomainsRequest,
    ValidateDomainsResponse,
    ValidationChallenge,
    ValidationMethod,
    ValidationScope,
    VALIDATION_SCOPE_HOST,
    VALIDATION_SCOPE_DOMAIN,
    VALIDATION_SCOPE_WILDCARD,
    VALIDATION_METHOD_DNS_CNAME,
    VALIDATION_METHOD_DNS_TXT,
    VALIDATION_METHOD_HTTP,
)
from .errors import (
    Error,
    ErrorDetail,
    ErrStructValidation,
    ErrAddDomains,
    ErrDeleteDomain,
    ErrDeleteDomains,
    ErrListDomains,
    ErrGetDomain,
    ErrSearchDomains,
    ErrValidateDomains,
    ErrInvalidateDomain,
    ErrInvalidateDomains,
    ErrDomainEmpty,
    ErrDomainTooLong,
    ErrDomainInvalidFmt,
    ERR_DOMAIN_NAME_VALIDATION_HINT,
)

__all__ = [
    # Client
    "Client",
    # Model classes
    "AddDomainsRequest",
    "AddDomainsResponse",
    "AddDomainError",
    "AddDomainSuccess",
    "CnameRecord",
    "DeleteDomainRequest",
    "DeleteDomainsRequest",
    "Domain",
    "DomainItem",
    "DomainStatusHistory",
    "GetDomainRequest",
    "GetDomainResponse",
    "HTTPFile",
    "HTTPRedirect",
    "InvalidateDomainRequest",
    "InvalidateDomainResponse",
    "InvalidateDomainsRequest",
    "InvalidateDomainsResponse",
    "Link",
    "ListDomainsRequest",
    "ListDomainsResponse",
    "Metadata",
    "SearchDomainItem",
    "SearchDomainsBody",
    "SearchDomainsRequest",
    "SearchDomainsResponse",
    "TXTRecord",
    "ValidateDomain",
    "ValidateDomainResponse",
    "ValidateDomainsRequest",
    "ValidateDomainsResponse",
    "ValidationChallenge",
    # Type aliases
    "ValidationScope",
    "ValidationMethod",
    # Validation scope constants
    "VALIDATION_SCOPE_HOST",
    "VALIDATION_SCOPE_DOMAIN",
    "VALIDATION_SCOPE_WILDCARD",
    # Validation method constants
    "VALIDATION_METHOD_DNS_CNAME",
    "VALIDATION_METHOD_DNS_TXT",
    "VALIDATION_METHOD_HTTP",
    # Error types
    "Error",
    "ErrorDetail",
    # Sentinel error constants
    "ErrStructValidation",
    "ErrAddDomains",
    "ErrDeleteDomain",
    "ErrDeleteDomains",
    "ErrListDomains",
    "ErrGetDomain",
    "ErrSearchDomains",
    "ErrValidateDomains",
    "ErrInvalidateDomain",
    "ErrInvalidateDomains",
    "ErrDomainEmpty",
    "ErrDomainTooLong",
    "ErrDomainInvalidFmt",
    "ERR_DOMAIN_NAME_VALIDATION_HINT",
]
