"""Akamai Cloudlets API client package.

Provides the :class:`Client` for managing Akamai Cloudlets policies,
policy versions, activations, load balancer origins, versions,
activations, and match rules.

Mirrors Go ``pkg/cloudlets`` — all public types from ``cloudlets.py``,
``models.py``, and ``errors.py`` are re-exported here so that consumers
can import directly::

    from akamai.edgegrid.cloudlets import Client, Policy, ErrGetPolicy
"""

from akamai.edgegrid.cloudlets.cloudlets import Client

from akamai.edgegrid.cloudlets.models import (  # pylint: disable=redefined-builtin
    # Response / domain model dataclasses
    Warning,
    Description,
    Origin,
    OriginResponse,
    PolicyInfo,
    PropertyInfo,
    PolicyActivation,
    Policy,
    DataCenter,
    LivenessSettings,
    LoadBalancerVersion,
    LoadBalancerVersionActivation,
    LoadBalancerActivation,
    CreatePolicyVersion,
    UpdatePolicyVersion,
    PolicyVersion,
    PolicyVersionActivation,
    CloudletsOrigin,
    NetworkStatus,
    PolicyProperty,
    UpdatePolicy,
    # Match criteria and forward settings
    Options,
    MatchCriteria,
    ObjectMatchValueObject,
    ObjectMatchValueSimple,
    ObjectMatchValueRange,
    ForwardSettingsALB,
    ForwardSettingsAS,
    ForwardSettingsPR,
    ForwardSettingsFR,
    # Match rule types
    MatchRuleALB,
    MatchRuleAP,
    MatchRuleAS,
    MatchRulePR,
    MatchRuleER,
    MatchRuleFR,
    MatchRuleRC,
    MatchRuleVP,
    # Match criteria type aliases
    MatchCriteriaALB,
    MatchCriteriaAP,
    MatchCriteriaAS,
    MatchCriteriaPR,
    MatchCriteriaER,
    MatchCriteriaFR,
    MatchCriteriaRC,
    MatchCriteriaVP,
    # Request dataclasses
    ListOriginsRequest,
    GetOriginRequest,
    CreateOriginRequest,
    UpdateOriginRequest,
    GetPolicyRequest,
    CreatePolicyRequest,
    UpdatePolicyRequest,
    ListPoliciesRequest,
    RemovePolicyRequest,
    CreateLoadBalancerVersionRequest,
    GetLoadBalancerVersionRequest,
    UpdateLoadBalancerVersionRequest,
    ListLoadBalancerVersionsRequest,
    ListLoadBalancerActivationsRequest,
    ActivateLoadBalancerVersionRequest,
    ListPolicyVersionsRequest,
    GetPolicyVersionRequest,
    CreatePolicyVersionRequest,
    DeletePolicyVersionRequest,
    UpdatePolicyVersionRequest,
    ListPolicyActivationsRequest,
    ActivatePolicyVersionRequest,
    GetPolicyPropertiesRequest,
    DeletePolicyPropertyRequest,
    GetPolicyVersionRuleRequest,
    CreatePolicyVersionRuleRequest,
    UpdatePolicyVersionRuleRequest,
    # Utility functions
    unmarshal_match_rule,
    unmarshal_match_rules,
    normalize_policy_activation_network,
    # Origin type constants
    ORIGIN_TYPE_ALL,
    ORIGIN_TYPE_CUSTOMER,
    ORIGIN_TYPE_APPLICATION_LOAD_BALANCER,
    ORIGIN_TYPE_NETSTORAGE,
    # Policy activation status constants
    POLICY_ACTIVATION_STATUS_ACTIVE,
    POLICY_ACTIVATION_STATUS_DEACTIVATED,
    POLICY_ACTIVATION_STATUS_INACTIVE,
    POLICY_ACTIVATION_STATUS_PENDING,
    POLICY_ACTIVATION_STATUS_FAILED,
    # Balancing type constants
    BALANCING_TYPE_WEIGHTED,
    BALANCING_TYPE_PERFORMANCE,
    # Load balancer activation status constants
    LB_ACTIVATION_STATUS_ACTIVE,
    LB_ACTIVATION_STATUS_DEACTIVATED,
    LB_ACTIVATION_STATUS_INACTIVE,
    LB_ACTIVATION_STATUS_PENDING,
    LB_ACTIVATION_STATUS_FAILED,
    # Load balancer activation network constants
    LB_ACTIVATION_NETWORK_STAGING,
    LB_ACTIVATION_NETWORK_PRODUCTION,
    NETWORK_PARAM_STAGING,
    NETWORK_PARAM_PRODUCTION,
    # Policy activation network constants
    POLICY_ACTIVATION_NETWORK_STAGING,
    POLICY_ACTIVATION_NETWORK_PRODUCTION,
    # Match rule type constants
    MATCH_RULE_TYPE_ALB,
    MATCH_RULE_TYPE_AP,
    MATCH_RULE_TYPE_AS,
    MATCH_RULE_TYPE_PR,
    MATCH_RULE_TYPE_ER,
    MATCH_RULE_TYPE_FR,
    MATCH_RULE_TYPE_RC,
    MATCH_RULE_TYPE_VP,
    # Match rule format constants
    MATCH_RULE_FORMAT_10,
    # Match operator constants
    MATCH_OPERATOR_CONTAINS,
    MATCH_OPERATOR_EXISTS,
    MATCH_OPERATOR_EQUALS,
    # Allow / Deny constants
    ALLOW,
    DENY,
    DENY_BRANDED,
    # CheckIPs constants
    CHECK_IPS_CONNECTING_IP,
    CHECK_IPS_XFF_HEADERS,
    CHECK_IPS_CONNECTING_IP_XFF_HEADERS,
    # Object match value type constants
    OBJECT_MATCH_VALUE_RANGE,
    OBJECT_MATCH_VALUE_SIMPLE,
    OBJECT_MATCH_VALUE_OBJECT,
)

from akamai.edgegrid.cloudlets.errors import (
    Error,
    # Struct validation sentinel
    ErrStructValidation,
    # Policy sentinels
    ErrListPolicies,
    ErrGetPolicy,
    ErrCreatePolicy,
    ErrRemovePolicy,
    ErrUpdatePolicy,
    # Policy version sentinels
    ErrListPolicyVersions,
    ErrGetPolicyVersion,
    ErrCreatePolicyVersion,
    ErrDeletePolicyVersion,
    ErrUpdatePolicyVersion,
    # Policy activation sentinels
    ErrListPolicyActivations,
    ErrActivatePolicyVersion,
    # Policy version rule sentinels
    ErrGetPolicyVersionRule,
    ErrCreatePolicyVersionRule,
    ErrUpdatePolicyVersionRule,
    # Policy property sentinels
    ErrGetPolicyProperties,
    ErrDeletePolicyProperty,
    # Origin / load balancer sentinels
    ErrListOrigins,
    ErrGetOrigin,
    ErrCreateOrigin,
    ErrUpdateOrigin,
    # Load balancer version sentinels
    ErrCreateLoadBalancerVersion,
    ErrGetLoadBalancerVersion,
    ErrUpdateLoadBalancerVersion,
    ErrListLoadBalancerVersions,
    # Load balancer activation sentinels
    ErrListLoadBalancerActivations,
    ErrActivateLoadBalancerVersion,
    # Match rule unmarshalling sentinels
    ErrUnmarshallMatchCriteriaALB,
    ErrUnmarshallMatchCriteriaAP,
    ErrUnmarshallMatchCriteriaAS,
    ErrUnmarshallMatchCriteriaPR,
    ErrUnmarshallMatchCriteriaER,
    ErrUnmarshallMatchCriteriaFR,
    ErrUnmarshallMatchCriteriaRC,
    ErrUnmarshallMatchCriteriaVP,
    ErrUnmarshallMatchRules,
)

__all__ = [
    # Client
    "Client",
    # Error class
    "Error",
    # Response / domain model dataclasses
    "Warning",
    "Description",
    "Origin",
    "OriginResponse",
    "PolicyInfo",
    "PropertyInfo",
    "PolicyActivation",
    "Policy",
    "DataCenter",
    "LivenessSettings",
    "LoadBalancerVersion",
    "LoadBalancerVersionActivation",
    "LoadBalancerActivation",
    "CreatePolicyVersion",
    "UpdatePolicyVersion",
    "PolicyVersion",
    "PolicyVersionActivation",
    "CloudletsOrigin",
    "NetworkStatus",
    "PolicyProperty",
    "UpdatePolicy",
    # Match criteria and forward settings
    "Options",
    "MatchCriteria",
    "ObjectMatchValueObject",
    "ObjectMatchValueSimple",
    "ObjectMatchValueRange",
    "ForwardSettingsALB",
    "ForwardSettingsAS",
    "ForwardSettingsPR",
    "ForwardSettingsFR",
    # Match rule types
    "MatchRuleALB",
    "MatchRuleAP",
    "MatchRuleAS",
    "MatchRulePR",
    "MatchRuleER",
    "MatchRuleFR",
    "MatchRuleRC",
    "MatchRuleVP",
    # Match criteria type aliases
    "MatchCriteriaALB",
    "MatchCriteriaAP",
    "MatchCriteriaAS",
    "MatchCriteriaPR",
    "MatchCriteriaER",
    "MatchCriteriaFR",
    "MatchCriteriaRC",
    "MatchCriteriaVP",
    # Request dataclasses
    "ListOriginsRequest",
    "GetOriginRequest",
    "CreateOriginRequest",
    "UpdateOriginRequest",
    "GetPolicyRequest",
    "CreatePolicyRequest",
    "UpdatePolicyRequest",
    "ListPoliciesRequest",
    "RemovePolicyRequest",
    "CreateLoadBalancerVersionRequest",
    "GetLoadBalancerVersionRequest",
    "UpdateLoadBalancerVersionRequest",
    "ListLoadBalancerVersionsRequest",
    "ListLoadBalancerActivationsRequest",
    "ActivateLoadBalancerVersionRequest",
    "ListPolicyVersionsRequest",
    "GetPolicyVersionRequest",
    "CreatePolicyVersionRequest",
    "DeletePolicyVersionRequest",
    "UpdatePolicyVersionRequest",
    "ListPolicyActivationsRequest",
    "ActivatePolicyVersionRequest",
    "GetPolicyPropertiesRequest",
    "DeletePolicyPropertyRequest",
    "GetPolicyVersionRuleRequest",
    "CreatePolicyVersionRuleRequest",
    "UpdatePolicyVersionRuleRequest",
    # Utility functions
    "unmarshal_match_rule",
    "unmarshal_match_rules",
    "normalize_policy_activation_network",
    # Origin type constants
    "ORIGIN_TYPE_ALL",
    "ORIGIN_TYPE_CUSTOMER",
    "ORIGIN_TYPE_APPLICATION_LOAD_BALANCER",
    "ORIGIN_TYPE_NETSTORAGE",
    # Policy activation status constants
    "POLICY_ACTIVATION_STATUS_ACTIVE",
    "POLICY_ACTIVATION_STATUS_DEACTIVATED",
    "POLICY_ACTIVATION_STATUS_INACTIVE",
    "POLICY_ACTIVATION_STATUS_PENDING",
    "POLICY_ACTIVATION_STATUS_FAILED",
    # Balancing type constants
    "BALANCING_TYPE_WEIGHTED",
    "BALANCING_TYPE_PERFORMANCE",
    # Load balancer activation status constants
    "LB_ACTIVATION_STATUS_ACTIVE",
    "LB_ACTIVATION_STATUS_DEACTIVATED",
    "LB_ACTIVATION_STATUS_INACTIVE",
    "LB_ACTIVATION_STATUS_PENDING",
    "LB_ACTIVATION_STATUS_FAILED",
    # Load balancer activation network constants
    "LB_ACTIVATION_NETWORK_STAGING",
    "LB_ACTIVATION_NETWORK_PRODUCTION",
    "NETWORK_PARAM_STAGING",
    "NETWORK_PARAM_PRODUCTION",
    # Policy activation network constants
    "POLICY_ACTIVATION_NETWORK_STAGING",
    "POLICY_ACTIVATION_NETWORK_PRODUCTION",
    # Match rule type constants
    "MATCH_RULE_TYPE_ALB",
    "MATCH_RULE_TYPE_AP",
    "MATCH_RULE_TYPE_AS",
    "MATCH_RULE_TYPE_PR",
    "MATCH_RULE_TYPE_ER",
    "MATCH_RULE_TYPE_FR",
    "MATCH_RULE_TYPE_RC",
    "MATCH_RULE_TYPE_VP",
    # Match rule format constants
    "MATCH_RULE_FORMAT_10",
    # Match operator constants
    "MATCH_OPERATOR_CONTAINS",
    "MATCH_OPERATOR_EXISTS",
    "MATCH_OPERATOR_EQUALS",
    # Allow / Deny constants
    "ALLOW",
    "DENY",
    "DENY_BRANDED",
    # CheckIPs constants
    "CHECK_IPS_CONNECTING_IP",
    "CHECK_IPS_XFF_HEADERS",
    "CHECK_IPS_CONNECTING_IP_XFF_HEADERS",
    # Object match value type constants
    "OBJECT_MATCH_VALUE_RANGE",
    "OBJECT_MATCH_VALUE_SIMPLE",
    "OBJECT_MATCH_VALUE_OBJECT",
    # Sentinel error constants
    "ErrStructValidation",
    "ErrListPolicies",
    "ErrGetPolicy",
    "ErrCreatePolicy",
    "ErrRemovePolicy",
    "ErrUpdatePolicy",
    "ErrListPolicyVersions",
    "ErrGetPolicyVersion",
    "ErrCreatePolicyVersion",
    "ErrDeletePolicyVersion",
    "ErrUpdatePolicyVersion",
    "ErrListPolicyActivations",
    "ErrActivatePolicyVersion",
    "ErrGetPolicyVersionRule",
    "ErrCreatePolicyVersionRule",
    "ErrUpdatePolicyVersionRule",
    "ErrGetPolicyProperties",
    "ErrDeletePolicyProperty",
    "ErrListOrigins",
    "ErrGetOrigin",
    "ErrCreateOrigin",
    "ErrUpdateOrigin",
    "ErrCreateLoadBalancerVersion",
    "ErrGetLoadBalancerVersion",
    "ErrUpdateLoadBalancerVersion",
    "ErrListLoadBalancerVersions",
    "ErrListLoadBalancerActivations",
    "ErrActivateLoadBalancerVersion",
    "ErrUnmarshallMatchCriteriaALB",
    "ErrUnmarshallMatchCriteriaAP",
    "ErrUnmarshallMatchCriteriaAS",
    "ErrUnmarshallMatchCriteriaPR",
    "ErrUnmarshallMatchCriteriaER",
    "ErrUnmarshallMatchCriteriaFR",
    "ErrUnmarshallMatchCriteriaRC",
    "ErrUnmarshallMatchCriteriaVP",
    "ErrUnmarshallMatchRules",
]
