"""Akamai Cloud Wrapper API client package.

See: https://techdocs.akamai.com/cloud-wrapper/reference/api
"""

from .cloudwrapper import CloudWrapperClient
from .errors import (
    Error,
    ErrorItem,
    ErrConfigurationNotFound,
    ErrDeletionNotAllowed,
    ErrStructValidation,
    ErrGetConfiguration,
    ErrListConfigurations,
    ErrCreateConfiguration,
    ErrUpdateConfiguration,
    ErrDeleteConfiguration,
    ErrActivateConfiguration,
    ErrListCapacities,
    ErrListLocations,
    ErrListAuthKeys,
    ErrListCDNProviders,
    ErrListProperties,
    ErrListOrigins,
)
from .models import (
    ActivateConfigurationRequest,
    BOCC,
    Behavior,
    CDN,
    CDNAuthKey,
    CDNProvider,
    Capacity,
    Child,
    ConfigLocationReq,
    ConfigLocationResp,
    Configuration,
    CreateConfigurationRequest,
    CreateConfigurationRequestBody,
    DataStreams,
    DeleteConfigurationRequest,
    GetConfigurationRequest,
    ListAuthKeysRequest,
    ListAuthKeysResponse,
    ListCDNProvidersResponse,
    ListCapacitiesRequest,
    ListCapacitiesResponse,
    ListConfigurationsResponse,
    ListLocationResponse,
    ListOriginsRequest,
    ListOriginsResponse,
    ListPropertiesRequest,
    ListPropertiesResponse,
    Location,
    LocationCapacity,
    MultiCDNAuthKey,
    MultiCDNSettings,
    Origin,
    Property,
    TrafficTypeItem,
    UpdateConfigurationRequest,
    UpdateConfigurationRequestBody,
)

__all__ = [
    # Client
    'CloudWrapperClient',
    # Errors
    'Error',
    'ErrorItem',
    'ErrConfigurationNotFound',
    'ErrDeletionNotAllowed',
    'ErrStructValidation',
    'ErrGetConfiguration',
    'ErrListConfigurations',
    'ErrCreateConfiguration',
    'ErrUpdateConfiguration',
    'ErrDeleteConfiguration',
    'ErrActivateConfiguration',
    'ErrListCapacities',
    'ErrListLocations',
    'ErrListAuthKeys',
    'ErrListCDNProviders',
    'ErrListProperties',
    'ErrListOrigins',
    # Models
    'ActivateConfigurationRequest',
    'BOCC',
    'Behavior',
    'CDN',
    'CDNAuthKey',
    'CDNProvider',
    'Capacity',
    'Child',
    'ConfigLocationReq',
    'ConfigLocationResp',
    'Configuration',
    'CreateConfigurationRequest',
    'CreateConfigurationRequestBody',
    'DataStreams',
    'DeleteConfigurationRequest',
    'GetConfigurationRequest',
    'ListAuthKeysRequest',
    'ListAuthKeysResponse',
    'ListCDNProvidersResponse',
    'ListCapacitiesRequest',
    'ListCapacitiesResponse',
    'ListConfigurationsResponse',
    'ListLocationResponse',
    'ListOriginsRequest',
    'ListOriginsResponse',
    'ListPropertiesRequest',
    'ListPropertiesResponse',
    'Location',
    'LocationCapacity',
    'MultiCDNAuthKey',
    'MultiCDNSettings',
    'Origin',
    'Property',
    'TrafficTypeItem',
    'UpdateConfigurationRequest',
    'UpdateConfigurationRequestBody',
]
