"""Akamai GTM (Global Traffic Management) API client package.

Provides access to the Akamai GTM V1_4 APIs for managing domains, properties,
datacenters, resources, AS maps, geographic maps, and CIDR maps.

See: https://techdocs.akamai.com/gtm/reference/api
"""

from .gtm import GTMClient
from .models import (
    # Domain types
    Domain,
    DomainItem,
    DomainQueryArgs,
    DomainRequest,
    GetDomainStatusRequest,
    GetDomainStatusResponse,
    GetDomainRequest,
    GetDomainResponse,
    CreateDomainRequest,
    CreateDomainResponse,
    UpdateDomainRequest,
    UpdateDomainResponse,
    DeleteDomainRequest,
    DeleteDomainResponse,
    DeleteDomainsRequest,
    DeleteDomainsRequestBody,
    DeleteDomainsResponse,
    DeleteDomainsStatusRequest,
    DeleteDomainsStatusResponse,
    NullFieldMapStruct,
    NullPerObjectAttributeStruct,
    # Property types
    Property,
    TrafficTarget,
    HTTPHeader,
    LivenessTest,
    StaticRRSet,
    PropertyRequest,
    GetPropertyRequest,
    GetPropertyResponse,
    ListPropertiesRequest,
    CreatePropertyRequest,
    CreatePropertyResponse,
    UpdatePropertyRequest,
    UpdatePropertyResponse,
    DeletePropertyRequest,
    DeletePropertyResponse,
    # Datacenter types
    Datacenter,
    DatacenterRequest,
    ListDatacentersRequest,
    GetDatacenterRequest,
    CreateDatacenterRequest,
    CreateDatacenterResponse,
    UpdateDatacenterRequest,
    UpdateDatacenterResponse,
    DeleteDatacenterRequest,
    DeleteDatacenterResponse,
    # Resource types
    Resource,
    ResourceInstance,
    ResourceRequest,
    ListResourcesRequest,
    GetResourceRequest,
    GetResourceResponse,
    CreateResourceRequest,
    CreateResourceResponse,
    UpdateResourceRequest,
    UpdateResourceResponse,
    DeleteResourceRequest,
    DeleteResourceResponse,
    # ASMap types
    ASMap,
    ASAssignment,
    ASMapRequest,
    ListASMapsRequest,
    GetASMapRequest,
    GetASMapResponse,
    CreateASMapRequest,
    CreateASMapResponse,
    UpdateASMapRequest,
    UpdateASMapResponse,
    DeleteASMapRequest,
    DeleteASMapResponse,
    # GeoMap types
    GeoMap,
    GeoAssignment,
    GeoMapRequest,
    ListGeoMapsRequest,
    GetGeoMapRequest,
    GetGeoMapResponse,
    CreateGeoMapRequest,
    CreateGeoMapResponse,
    UpdateGeoMapRequest,
    UpdateGeoMapResponse,
    DeleteGeoMapRequest,
    DeleteGeoMapResponse,
    # CIDRMap types
    CIDRMap,
    CIDRAssignment,
    CIDRMapRequest,
    ListCIDRMapsRequest,
    GetCIDRMapRequest,
    GetCIDRMapResponse,
    CreateCIDRMapRequest,
    CreateCIDRMapResponse,
    UpdateCIDRMapRequest,
    UpdateCIDRMapResponse,
    DeleteCIDRMapRequest,
    DeleteCIDRMapResponse,
    # Common types
    ResponseStatus,
    Link,
    LoadObject,
    DatacenterBase,
)
from .errors import (
    Error,
    ErrNotFound,
    ErrNoDatacenterAssignedToMap,
    ErrDomainNotFound,
    ErrGetDomainStatus,
    ErrGetDomain,
    ErrCreateDomain,
    ErrUpdateDomain,
    ErrDeleteDomain,
    ErrDeleteDomains,
    ErrGetDeleteDomainsStatus,
    ErrGetProperty,
    ErrListProperties,
    ErrCreateProperty,
    ErrUpdateProperty,
    ErrDeleteProperty,
    ErrListDatacenters,
    ErrGetDatacenter,
    ErrCreateDatacenter,
    ErrUpdateDatacenter,
    ErrDeleteDatacenter,
    ErrListResources,
    ErrGetResource,
    ErrCreateResource,
    ErrUpdateResource,
    ErrDeleteResource,
    ErrListASMaps,
    ErrGetASMap,
    ErrCreateASMap,
    ErrUpdateASMap,
    ErrDeleteASMap,
    ErrListGeoMaps,
    ErrGetGeoMap,
    ErrCreateGeoMap,
    ErrUpdateGeoMap,
    ErrDeleteGeoMap,
    ErrListCIDRMaps,
    ErrGetCIDRMap,
    ErrCreateCIDRMap,
    ErrUpdateCIDRMap,
    ErrDeleteCIDRMap,
)

__all__ = [
    # Client
    "GTMClient",
    # Domain types
    "Domain",
    "DomainItem",
    "DomainQueryArgs",
    "DomainRequest",
    "GetDomainStatusRequest",
    "GetDomainStatusResponse",
    "GetDomainRequest",
    "GetDomainResponse",
    "CreateDomainRequest",
    "CreateDomainResponse",
    "UpdateDomainRequest",
    "UpdateDomainResponse",
    "DeleteDomainRequest",
    "DeleteDomainResponse",
    "DeleteDomainsRequest",
    "DeleteDomainsRequestBody",
    "DeleteDomainsResponse",
    "DeleteDomainsStatusRequest",
    "DeleteDomainsStatusResponse",
    "NullFieldMapStruct",
    "NullPerObjectAttributeStruct",
    # Property types
    "Property",
    "TrafficTarget",
    "HTTPHeader",
    "LivenessTest",
    "StaticRRSet",
    "PropertyRequest",
    "GetPropertyRequest",
    "GetPropertyResponse",
    "ListPropertiesRequest",
    "CreatePropertyRequest",
    "CreatePropertyResponse",
    "UpdatePropertyRequest",
    "UpdatePropertyResponse",
    "DeletePropertyRequest",
    "DeletePropertyResponse",
    # Datacenter types
    "Datacenter",
    "DatacenterRequest",
    "ListDatacentersRequest",
    "GetDatacenterRequest",
    "CreateDatacenterRequest",
    "CreateDatacenterResponse",
    "UpdateDatacenterRequest",
    "UpdateDatacenterResponse",
    "DeleteDatacenterRequest",
    "DeleteDatacenterResponse",
    # Resource types
    "Resource",
    "ResourceInstance",
    "ResourceRequest",
    "ListResourcesRequest",
    "GetResourceRequest",
    "GetResourceResponse",
    "CreateResourceRequest",
    "CreateResourceResponse",
    "UpdateResourceRequest",
    "UpdateResourceResponse",
    "DeleteResourceRequest",
    "DeleteResourceResponse",
    # ASMap types
    "ASMap",
    "ASAssignment",
    "ASMapRequest",
    "ListASMapsRequest",
    "GetASMapRequest",
    "GetASMapResponse",
    "CreateASMapRequest",
    "CreateASMapResponse",
    "UpdateASMapRequest",
    "UpdateASMapResponse",
    "DeleteASMapRequest",
    "DeleteASMapResponse",
    # GeoMap types
    "GeoMap",
    "GeoAssignment",
    "GeoMapRequest",
    "ListGeoMapsRequest",
    "GetGeoMapRequest",
    "GetGeoMapResponse",
    "CreateGeoMapRequest",
    "CreateGeoMapResponse",
    "UpdateGeoMapRequest",
    "UpdateGeoMapResponse",
    "DeleteGeoMapRequest",
    "DeleteGeoMapResponse",
    # CIDRMap types
    "CIDRMap",
    "CIDRAssignment",
    "CIDRMapRequest",
    "ListCIDRMapsRequest",
    "GetCIDRMapRequest",
    "GetCIDRMapResponse",
    "CreateCIDRMapRequest",
    "CreateCIDRMapResponse",
    "UpdateCIDRMapRequest",
    "UpdateCIDRMapResponse",
    "DeleteCIDRMapRequest",
    "DeleteCIDRMapResponse",
    # Common types
    "ResponseStatus",
    "Link",
    "LoadObject",
    "DatacenterBase",
    # Error class
    "Error",
    # Sentinel error constants
    "ErrNotFound",
    "ErrNoDatacenterAssignedToMap",
    "ErrDomainNotFound",
    "ErrGetDomainStatus",
    "ErrGetDomain",
    "ErrCreateDomain",
    "ErrUpdateDomain",
    "ErrDeleteDomain",
    "ErrDeleteDomains",
    "ErrGetDeleteDomainsStatus",
    "ErrGetProperty",
    "ErrListProperties",
    "ErrCreateProperty",
    "ErrUpdateProperty",
    "ErrDeleteProperty",
    "ErrListDatacenters",
    "ErrGetDatacenter",
    "ErrCreateDatacenter",
    "ErrUpdateDatacenter",
    "ErrDeleteDatacenter",
    "ErrListResources",
    "ErrGetResource",
    "ErrCreateResource",
    "ErrUpdateResource",
    "ErrDeleteResource",
    "ErrListASMaps",
    "ErrGetASMap",
    "ErrCreateASMap",
    "ErrUpdateASMap",
    "ErrDeleteASMap",
    "ErrListGeoMaps",
    "ErrGetGeoMap",
    "ErrCreateGeoMap",
    "ErrUpdateGeoMap",
    "ErrDeleteGeoMap",
    "ErrListCIDRMaps",
    "ErrGetCIDRMap",
    "ErrCreateCIDRMap",
    "ErrUpdateCIDRMap",
    "ErrDeleteCIDRMap",
]
