"""API Definitions API client for Akamai API Gateway.

Provides access to the Akamai API Definitions API for managing
API endpoints, versions, activations, and resource operations.

Mirrors Go ``pkg/apidefinitions`` which defines the ``APIDefinitions``
interface with 17 endpoint methods, request/response model structs,
sentinel error constants, and a ``Client()`` factory function.

Usage::

    >>> from akamai.edgegrid import EdgeGridAuth, EdgeRc
    >>> from akamai.edgegrid.session import Session
    >>> from akamai.edgegrid.apidefinitions import Client, ListEndpointsRequest
    >>>
    >>> edgerc = EdgeRc("~/.edgerc")
    >>> session = Session(edgerc=edgerc, section="default")
    >>> client = Client(session)
    >>> response = client.list_endpoints(ListEndpointsRequest(contract_id="ctr_1"))
"""

# Client class — mirrors Go pkg/apidefinitions.Client() factory
from akamai.edgegrid.apidefinitions.apidefinitions import Client

# Error class and sentinel error constants
from akamai.edgegrid.apidefinitions.errors import (
    Error,
    ErrGetEndpoint,
    ErrListEndpoints,
    ErrRegisterEndpoint,
    ErrRegisterEndpointFromFile,
    ErrListUserEntitlements,
    ErrShowEndpoint,
    ErrHideEndpoint,
    ErrDeleteEndpoint,
    ErrGetEndpointVersion,
    ErrDeleteEndpointVersion,
    ErrListEndpointVersions,
    ErrCloneEndpointVersion,
    ErrUpdateEndpointVersion,
    ErrVerifyVersion,
    ErrActivateVersion,
    ErrDeactivateVersion,
    ErrSearchResourceAndOperations,
)

# Model classes, typed string constants, and type aliases
from akamai.edgegrid.apidefinitions.models import (
    # --- Activation network / status constants (activations.go) ---
    ACTIVATION_NETWORK_STAGING,
    ACTIVATION_NETWORK_PRODUCTION,
    ACTIVATION_STATUS_PENDING,
    ACTIVATION_STATUS_ACTIVE,
    ACTIVATION_STATUS_DEACTIVATED,
    ACTIVATION_STATUS_FAILED,
    SEVERITY_ERROR,
    SEVERITY_WARNING,
    # --- Endpoint version sort / visibility constants ---
    DESCRIPTION_SORT,
    VERSION_NUMBER_SORT,
    UPDATE_DATE_SORT,
    UPDATED_BY_SORT,
    BASED_ON_SORT,
    STAGING_STATUS_SORT,
    PRODUCTION_STATUS_SORT,
    ASC_SORT_ORDER,
    DESC_SORT_ORDER,
    ALL_VISIBILITY,
    ONLY_HIDDEN_VISIBILITY,
    ONLY_VISIBLE_VISIBILITY,
    # --- Endpoint constants (endpoints.go) ---
    API_RESOURCE_METHODS_GET,
    API_RESOURCE_METHODS_PUT,
    API_RESOURCE_METHODS_POST,
    API_RESOURCE_METHODS_DELETE,
    API_RESOURCE_METHODS_HEAD,
    API_RESOURCE_METHODS_PATCH,
    API_RESOURCE_METHODS_OPTIONS,
    MAX_BODY_SIZE_SIZE_6K,
    MAX_BODY_SIZE_SIZE_8K,
    MAX_BODY_SIZE_SIZE_12K,
    MAX_BODY_SIZE_SIZE_16K,
    MAX_BODY_SIZE_NO_LIMIT,
    MAX_BODY_SIZE_NULL,
    API_PARAMETER_LOCATION_QUERY,
    API_PARAMETER_LOCATION_COOKIE,
    API_PARAMETER_LOCATION_HEADER,
    API_PARAMETER_LOCATION_PATH,
    API_PARAMETER_LOCATION_BODY,
    API_PARAMETER_TYPE_STRING,
    API_PARAMETER_TYPE_INTEGER,
    API_PARAMETER_TYPE_NUMBER,
    API_PARAMETER_TYPE_BOOLEAN,
    API_PARAMETER_TYPE_JSONXML,
    API_KEY_LOCATION_COOKIE,
    API_KEY_LOCATION_HEADER,
    API_KEY_LOCATION_QUERY,
    CONSUME_TYPE_JSON,
    CONSUME_TYPE_XML,
    CONSUME_TYPE_JSONXML,
    CONSUME_TYPE_URLENCODED,
    CONSUME_TYPE_JSON_URLENCODED,
    CONSUME_TYPE_XML_URLENCODED,
    CONSUME_TYPE_JSONXML_URLENCODED,
    CONSUME_TYPE_ANY,
    CONSUME_TYPE_NONE,
    IMPORT_FILE_FORMAT_RAML,
    IMPORT_FILE_FORMAT_SWAGGER,
    IMPORT_FILE_SOURCE_URL,
    IMPORT_FILE_SOURCE_BASE64,
    API_ENDPOINT_SCHEME_HTTP,
    API_ENDPOINT_SCHEME_HTTPS,
    API_ENDPOINT_SCHEME_HTTP_HTTPS,
    API_SOURCE_USER,
    API_SOURCE_API_DISCOVERY,
    SOURCE_TYPE_SWAGGER,
    SOURCE_TYPE_RAML,
    NAME_SORT,
    UPDATE_ENDPOINT_DATE_SORT,
    VERSION_PREFERENCE_LAST_UPDATED,
    VERSION_PREFERENCE_ACTIVATED_FIRST,
    API_VERSION_LOCATION_HEADER,
    API_VERSION_LOCATION_BASE_PATH,
    API_VERSION_LOCATION_QUERY,
    # --- Custom types ---
    RestrictionsBool,
    # --- Leaf model dataclasses ---
    LengthRestriction,
    RangeRestriction,
    NumberRangeRestriction,
    ArrayRestriction,
    XMLConversionRule,
    ResponseRestriction,
    AllowMethodUndefinedParameters,
    MethodRestrictions,
    SecuritySchemeDetail,
    SecurityScheme,
    Source,
    APIVersionInfo,
    APIParameterRestriction,
    EndpointError,
    VersionState,
    APIMethod,
    APIResourceBaseInfo,
    APIParameter,
    APIResourceMethod,
    APIResourceMethodRes,
    APIResource,
    APIResourceRes,
    APIParameterRes,
    AkamaiSecurityRestrictions,
    APISourceDiff,
    # --- Endpoint hierarchy ---
    Endpoint,
    EndpointDetail,
    EndpointWithResources,
    # --- Endpoint request/response models ---
    RegisterEndpointRequest,
    RegisterEndpointFromFileRequest,
    ShowEndpointRequest,
    ShowEndpointResponse,
    HideEndpointRequest,
    HideEndpointResponse,
    GetEndpointRequest,
    DeleteEndpointRequest,
    EndpointResponse,
    ListEndpointsRequest,
    RegisterEndpointResponse,
    ListEndpointsResponse,
    # --- Endpoint version models ---
    ListEndpointVersionsRequest,
    EndpointVersionRequest,
    UpdateEndpointVersionRequest,
    ListEndpointVersionsResponse,
    APIVersion,
    EndpointVersionResponse,
    UpdateEndpointVersionRequestBody,
    # --- Activation models ---
    VerifyVersionRequestBody,
    VerifyVersionRequest,
    ActivationRequestBody,
    ActivateVersionRequest,
    ActivateVersionResponse,
    DeactivateVersionRequest,
    DeactivateVersionResponse,
    VerifyVersionAlert,
    # --- Resource operation models ---
    VersionDetail,
    Condition,
    OperationMetadata,
    ParameterDetail,
    OperationParameter,
    ResourceMetadata,
    ResourceMethod,
    Operation,
    Resource,
    APIEndpoint,
    SearchResourceOperationsResponse,
    # --- Type aliases ---
    GetEndpointResponse,
    RegisterEndpointFromFileResponse,
    ListUserEntitlementsResponse,
    DeleteEndpointVersionRequest,
    CloneEndpointVersionRequest,
    GetEndpointVersionRequest,
    GetEndpointVersionResponse,
    CloneEndpointVersionResponse,
    UpdateEndpointVersionResponse,
    VerifyVersionResponse,
)

__all__ = [
    # Client
    "Client",
    # Error class and sentinels
    "Error",
    "ErrGetEndpoint",
    "ErrListEndpoints",
    "ErrRegisterEndpoint",
    "ErrRegisterEndpointFromFile",
    "ErrListUserEntitlements",
    "ErrShowEndpoint",
    "ErrHideEndpoint",
    "ErrDeleteEndpoint",
    "ErrGetEndpointVersion",
    "ErrDeleteEndpointVersion",
    "ErrListEndpointVersions",
    "ErrCloneEndpointVersion",
    "ErrUpdateEndpointVersion",
    "ErrVerifyVersion",
    "ErrActivateVersion",
    "ErrDeactivateVersion",
    "ErrSearchResourceAndOperations",
    # Constants — activation network / status
    "ACTIVATION_NETWORK_STAGING",
    "ACTIVATION_NETWORK_PRODUCTION",
    "ACTIVATION_STATUS_PENDING",
    "ACTIVATION_STATUS_ACTIVE",
    "ACTIVATION_STATUS_DEACTIVATED",
    "ACTIVATION_STATUS_FAILED",
    "SEVERITY_ERROR",
    "SEVERITY_WARNING",
    # Constants — endpoint version sort / visibility
    "DESCRIPTION_SORT",
    "VERSION_NUMBER_SORT",
    "UPDATE_DATE_SORT",
    "UPDATED_BY_SORT",
    "BASED_ON_SORT",
    "STAGING_STATUS_SORT",
    "PRODUCTION_STATUS_SORT",
    "ASC_SORT_ORDER",
    "DESC_SORT_ORDER",
    "ALL_VISIBILITY",
    "ONLY_HIDDEN_VISIBILITY",
    "ONLY_VISIBLE_VISIBILITY",
    # Constants — endpoint
    "API_RESOURCE_METHODS_GET",
    "API_RESOURCE_METHODS_PUT",
    "API_RESOURCE_METHODS_POST",
    "API_RESOURCE_METHODS_DELETE",
    "API_RESOURCE_METHODS_HEAD",
    "API_RESOURCE_METHODS_PATCH",
    "API_RESOURCE_METHODS_OPTIONS",
    "MAX_BODY_SIZE_SIZE_6K",
    "MAX_BODY_SIZE_SIZE_8K",
    "MAX_BODY_SIZE_SIZE_12K",
    "MAX_BODY_SIZE_SIZE_16K",
    "MAX_BODY_SIZE_NO_LIMIT",
    "MAX_BODY_SIZE_NULL",
    "API_PARAMETER_LOCATION_QUERY",
    "API_PARAMETER_LOCATION_COOKIE",
    "API_PARAMETER_LOCATION_HEADER",
    "API_PARAMETER_LOCATION_PATH",
    "API_PARAMETER_LOCATION_BODY",
    "API_PARAMETER_TYPE_STRING",
    "API_PARAMETER_TYPE_INTEGER",
    "API_PARAMETER_TYPE_NUMBER",
    "API_PARAMETER_TYPE_BOOLEAN",
    "API_PARAMETER_TYPE_JSONXML",
    "API_KEY_LOCATION_COOKIE",
    "API_KEY_LOCATION_HEADER",
    "API_KEY_LOCATION_QUERY",
    "CONSUME_TYPE_JSON",
    "CONSUME_TYPE_XML",
    "CONSUME_TYPE_JSONXML",
    "CONSUME_TYPE_URLENCODED",
    "CONSUME_TYPE_JSON_URLENCODED",
    "CONSUME_TYPE_XML_URLENCODED",
    "CONSUME_TYPE_JSONXML_URLENCODED",
    "CONSUME_TYPE_ANY",
    "CONSUME_TYPE_NONE",
    "IMPORT_FILE_FORMAT_RAML",
    "IMPORT_FILE_FORMAT_SWAGGER",
    "IMPORT_FILE_SOURCE_URL",
    "IMPORT_FILE_SOURCE_BASE64",
    "API_ENDPOINT_SCHEME_HTTP",
    "API_ENDPOINT_SCHEME_HTTPS",
    "API_ENDPOINT_SCHEME_HTTP_HTTPS",
    "API_SOURCE_USER",
    "API_SOURCE_API_DISCOVERY",
    "SOURCE_TYPE_SWAGGER",
    "SOURCE_TYPE_RAML",
    "NAME_SORT",
    "UPDATE_ENDPOINT_DATE_SORT",
    "VERSION_PREFERENCE_LAST_UPDATED",
    "VERSION_PREFERENCE_ACTIVATED_FIRST",
    "API_VERSION_LOCATION_HEADER",
    "API_VERSION_LOCATION_BASE_PATH",
    "API_VERSION_LOCATION_QUERY",
    # Custom types
    "RestrictionsBool",
    # Model dataclasses
    "LengthRestriction",
    "RangeRestriction",
    "NumberRangeRestriction",
    "ArrayRestriction",
    "XMLConversionRule",
    "ResponseRestriction",
    "AllowMethodUndefinedParameters",
    "MethodRestrictions",
    "SecuritySchemeDetail",
    "SecurityScheme",
    "Source",
    "APIVersionInfo",
    "APIParameterRestriction",
    "EndpointError",
    "VersionState",
    "APIMethod",
    "APIResourceBaseInfo",
    "APIParameter",
    "APIResourceMethod",
    "APIResourceMethodRes",
    "APIResource",
    "APIResourceRes",
    "APIParameterRes",
    "AkamaiSecurityRestrictions",
    "APISourceDiff",
    "Endpoint",
    "EndpointDetail",
    "EndpointWithResources",
    "RegisterEndpointRequest",
    "RegisterEndpointFromFileRequest",
    "ShowEndpointRequest",
    "ShowEndpointResponse",
    "HideEndpointRequest",
    "HideEndpointResponse",
    "GetEndpointRequest",
    "DeleteEndpointRequest",
    "EndpointResponse",
    "ListEndpointsRequest",
    "RegisterEndpointResponse",
    "ListEndpointsResponse",
    "ListEndpointVersionsRequest",
    "EndpointVersionRequest",
    "UpdateEndpointVersionRequest",
    "ListEndpointVersionsResponse",
    "APIVersion",
    "EndpointVersionResponse",
    "UpdateEndpointVersionRequestBody",
    "VerifyVersionRequestBody",
    "VerifyVersionRequest",
    "ActivationRequestBody",
    "ActivateVersionRequest",
    "ActivateVersionResponse",
    "DeactivateVersionRequest",
    "DeactivateVersionResponse",
    "VerifyVersionAlert",
    "VersionDetail",
    "Condition",
    "OperationMetadata",
    "ParameterDetail",
    "OperationParameter",
    "ResourceMetadata",
    "ResourceMethod",
    "Operation",
    "Resource",
    "APIEndpoint",
    "SearchResourceOperationsResponse",
    # Type aliases
    "GetEndpointResponse",
    "RegisterEndpointFromFileResponse",
    "ListUserEntitlementsResponse",
    "DeleteEndpointVersionRequest",
    "CloneEndpointVersionRequest",
    "GetEndpointVersionRequest",
    "GetEndpointVersionResponse",
    "CloneEndpointVersionResponse",
    "UpdateEndpointVersionResponse",
    "VerifyVersionResponse",
]
